extends GdUnitTestSuite
## The GDScript side of the `state_phi` / `logit` twin pin — the SAME fixture
## the Rust crate asserts in `core/nml-core/tests/state_phi_twin.rs`, so a
## drift in either twin fails its own side. Fixture generated by
## `tools/policy_twin/gen_state_phi_twin.py` (never by hand).

const FIXTURE := "res://test/fixtures/policy_twin/state_phi_twin.json"
const TOL := 1e-9


func test_state_phi_and_logit_match_the_pinned_fixture() -> void:
	var pins: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(FIXTURE))
	var net: Dictionary = pins["net"]
	var candidate: Array = pins["candidate"]
	for c in pins["cases"]:
		var case: Dictionary = c
		var board: Array = (pins["boards"] as Dictionary)[case["board"]]
		var side := int(case["side"])
		var phi := PolicyOrder.state_phi(board, side)
		var want_phi: Array = case["state_phi"]
		assert_int(phi.size()).is_equal(93)
		for i in phi.size():
			assert_float(absf(float(phi[i]) - float(want_phi[i]))).is_less_equal(TOL)
		var got := PolicyOrder.logit(net, phi, candidate)
		assert_float(absf(got - float(case["logit"]))).is_less_equal(TOL)
