extends GdUnitTestSuite
## Solo-AI wave 5 — RulesRegistry: the system-scoped mechanics-map loader (assets/solo/
## rules_mechanics_<system>.json, generated by tools/rules_mechanics_export.py). Proves the HARD
## invariant (lookup by (system, faction, name) with a common fallback — never name-only across
## systems), the system-scoped parameter divergences, the derived modeled/decision token sets, and
## the committed maps' text-hygiene (no OPR rule bodies in the public repo).


func _unit_with(rules: Array, system: String = "", faction: String = "", defense: int = 4) -> GameUnit:
	var u := GameUnit.new()
	u.unit_id = "t_%d" % rules.size()
	u.unit_properties = {"player_id": 2, "name": "T", "quality": 4, "defense": defense,
		"special_rules": rules}
	if not system.is_empty():
		u.unit_properties["game_system"] = system
	if not faction.is_empty():
		u.unit_properties["faction_folder"] = faction
	var m := ModelInstance.new()
	m.is_alive = true
	u.models.append(m)
	return u


func test_all_five_system_maps_load() -> void:
	for s in RulesRegistry.SYSTEMS:
		var m := RulesRegistry.map_for(str(s))
		assert_bool(m.is_empty()).override_failure_message("map missing for %s" % s).is_false()
		assert_bool((m.get("common", {}) as Dictionary).is_empty()).is_false()
		assert_bool((m.get("modeled", []) as Array).is_empty()).is_false()


func test_lookup_falls_back_from_faction_to_common() -> void:
	# "AP" is a core rule: not in the faction section → resolved via the system's common section.
	var entry := RulesRegistry.lookup("gf", "human_defense_force", "AP")
	assert_str(str(entry.get("primitive", ""))).is_equal("AP")
	# A faction-level rule resolves from the faction's own section.
	var shred := RulesRegistry.lookup("gf", "alien_hives", "Shred")
	assert_str(str(shred.get("primitive", ""))).is_equal("Shred")
	# Unknown rules yield an empty entry (callers use their fallbacks).
	assert_bool(RulesRegistry.lookup("gf", "alien_hives", "No Such Rule").is_empty()).is_true()


func test_system_scoping_banner_and_musician_params_diverge() -> void:
	# THE cross-system divergence proof (wave-5 gate 4): the full-scale games (GF / AoF / AoF
	# Regiments) grant Banner/Musician to the bearer's UNIT; the skirmish-scale games (GFF / AoF
	# Skirmish) rewrite them to "bearer + up to 3 picked friendly units". Same rule NAME — different
	# parameters per system, so a name-only lookup would be WRONG.
	for s in ["gf", "aof", "aofr"]:
		assert_str(str(RulesRegistry.param(str(s), "", "Banner", "scope", ""))).is_equal("unit")
		assert_str(str(RulesRegistry.param(str(s), "", "Musician", "scope", ""))).is_equal("unit")
		assert_int(int(RulesRegistry.param(str(s), "", "Banner", "picked_units", 0))).is_equal(0)
	for s in ["gff", "aofs"]:
		assert_str(str(RulesRegistry.param(str(s), "", "Banner", "scope", ""))).is_equal("picked")
		assert_str(str(RulesRegistry.param(str(s), "", "Musician", "scope", ""))).is_equal("picked")
		assert_int(int(RulesRegistry.param(str(s), "", "Banner", "picked_units", 0))).is_equal(3)
	# The bonus itself is identical everywhere (+1) — only the scope diverges.
	for s in RulesRegistry.SYSTEMS:
		assert_int(int(RulesRegistry.param(str(s), "", "Banner", "morale_bonus", 0))).is_equal(1)


func test_modeled_tokens_are_system_scoped() -> void:
	# Royal Legion (Mummified Undead) is an AoF-family army-book rule: modeled in aof — and since
	# the coverage wave, gf carries the PRIMITIVE too (Lustbound aliases it), so the token appears
	# there as well. System scoping still holds at LOOKUP level (per (system, faction, name)).
	assert_bool(RulesRegistry.modeled_tokens("aof").has("Royal Legion")).is_true()
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Royal Legion")).is_true()   # via the Lustbound alias
	assert_bool(RulesRegistry.lookup("gf", "battle_brothers", "Royal Legion").is_empty()).is_true()
	# The shared core primitives are modeled everywhere, incl. the wave-5 set.
	for s in RulesRegistry.SYSTEMS:
		var tokens := RulesRegistry.modeled_tokens(str(s))
		for t in ["AP", "Tough", "Shred", "Indirect", "Banner", "Musician", "Sergeant", "Limited", "Armor"]:
			assert_bool(tokens.has(t)).override_failure_message("%s missing in %s" % [t, s]).is_true()
		assert_bool(RulesRegistry.decision_tokens(str(s)).has("Indirect")).is_true()


func test_param_returns_fallback_when_absent() -> void:
	assert_int(int(RulesRegistry.param("gf", "", "AP", "no_such_param", 42))).is_equal(42)
	assert_int(int(RulesRegistry.param("gf", "", "No Such Rule", "x", 7))).is_equal(7)
	# Unknown system slugs normalize to the default system instead of crashing.
	assert_str(RulesRegistry.normalize_system("bogus")).is_equal(RulesRegistry.DEFAULT_SYSTEM)
	assert_str(RulesRegistry.normalize_system("AOFS ")).is_equal("aofs")


func test_unit_addressing_reads_import_properties() -> void:
	var u := _unit_with(["Banner"], "gff", "human_empire")
	assert_str(RulesRegistry.system_of_unit(u)).is_equal("gff")
	assert_str(RulesRegistry.faction_of_unit(u)).is_equal("human_empire")
	# The unit-addressed param resolves under ITS system: gff Banner = the picked-units variant.
	assert_str(str(RulesRegistry.unit_param(u, "Banner", "scope", ""))).is_equal("picked")
	# A unit without import metadata falls back to the default system, not a crash.
	var bare := _unit_with(["Banner"])
	assert_str(RulesRegistry.system_of_unit(bare)).is_equal(RulesRegistry.DEFAULT_SYSTEM)
	assert_str(str(RulesRegistry.unit_param(bare, "Banner", "scope", ""))).is_equal("unit")


func test_unit_rule_active_is_system_scoped() -> void:
	# Banner is a core rule → active in every system for a bearer.
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Banner"], "gf"), "Banner")).is_true()
	# Royal Legion: active for the AoF book that fields it, NOT for a gf unit (no gf book has it).
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Royal Legion"], "aof", "mummified_undead"), "Royal Legion")).is_true()
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Royal Legion"], "gf", "human_defense_force"), "Royal Legion")).is_false()
	# Not carrying the rule at all → inactive, whatever the map says.
	assert_bool(RulesRegistry.unit_rule_active(_unit_with([], "gf"), "Banner")).is_false()


func test_committed_maps_carry_no_rule_texts() -> void:
	# Public-repo IP guard (maintainer-ruled): the maps are DERIVED mechanics — rule names + our own
	# primitive/param encoding. No entry may carry a text-ish key, and no param string may be prose.
	var forbidden := ["official_text", "text", "description", "reason", "citation", "_license"]
	for s in RulesRegistry.SYSTEMS:
		var m := RulesRegistry.map_for(str(s))
		var sections: Array = [m.get("common", {})]
		for fmap in (m.get("factions", {}) as Dictionary).values():
			sections.append(fmap)
		for section in sections:
			for rule_name in (section as Dictionary):
				var entry := (section as Dictionary)[rule_name] as Dictionary
				for key in forbidden:
					assert_bool(entry.has(key)).override_failure_message(
						"%s/%s carries forbidden key %s" % [s, rule_name, key]).is_false()
				for pv in (entry.get("params", {}) as Dictionary).values():
					if pv is String:
						assert_bool((pv as String).length() <= 24 and not (pv as String).contains(". ")) \
							.override_failure_message("prose-like param in %s/%s: %s" % [s, rule_name, pv]).is_true()


func test_regen_and_fearless_params_match_the_wave14_constants() -> void:
	# The byte-identical seam: where wave-1..4 dice math now READS the map, the data must equal the
	# constants it replaced (Regeneration 5+, Self-Repair 6+, Fearless 4+, Royal Legion +4").
	assert_int(int(RulesRegistry.param("gf", "", "Regeneration", "ignore_target", 0))).is_equal(5)
	assert_int(int(RulesRegistry.param("gf", "robot_legions", "Self-Repair", "ignore_target", 0))).is_equal(6)
	assert_int(int(RulesRegistry.param("gf", "", "Fearless", "recover_target", 0))).is_equal(4)
	assert_int(int(RulesRegistry.param("aof", "mummified_undead", "Royal Legion", "range_bonus_in", 0))).is_equal(4)


func test_resistance_is_regeneration_family_with_spell_threshold() -> void:
	# Wave-5 coverage push (2026-07-17, "primitive families first" grill): Resistance = the Regeneration
	# family — ignore normal wounds on 6+, but SPELL wounds on a far more generous 2+ (official AoF/GF
	# text). This is the thin vertical slice that proves the full data pipeline end-to-end: source
	# registry -> text-free export -> committed map -> lookup. alien_hives is one gf book that fields it.
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Resistance", "ignore_target", 0))).is_equal(6)
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Resistance", "ignore_target_spell", 0))).is_equal(2)
	# Derived-modeled + system-scoped active for a bearer whose book actually fields it.
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Resistance")).is_true()
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Resistance"], "gf", "alien_hives"), "Resistance")).is_true()


func test_conditional_ap_family_resolves_target_property_params() -> void:
	# Wave-5 "primitive families first" (2026-07-18): the target-property AP rules each carry their own
	# {ap_bonus, condition, threshold} in the map, all consumed by the one AiCombatMath.conditional_ap_bonus
	# reader. Data-pipeline proof (source -> export -> map) for the conditional-AP family.
	assert_int(int(RulesRegistry.param("gf", "blood_prime_brothers", "Shatter", "ap_bonus", 0))).is_equal(2)
	assert_str(str(RulesRegistry.param("gf", "blood_prime_brothers", "Shatter", "condition", ""))).is_equal("vs_tough_ge")
	assert_int(int(RulesRegistry.param("gf", "custodian_brothers", "Tear", "threshold", 0))).is_equal(9)
	assert_bool(bool(RulesRegistry.param("gf", "blood_prime_brothers", "Melee Slayer", "charge_only", false))).is_true()
	assert_str(str(RulesRegistry.param("gf", "blessed_sisters", "Disintegrate", "condition", ""))).is_equal("vs_armor")
	# Piercing Assault: same reader, charge-gated condition (a reuse case, no new game code).
	assert_str(str(RulesRegistry.param("gf", "blessed_sisters", "Piercing Assault", "condition", ""))).is_equal("on_charge")
	assert_int(int(RulesRegistry.param("gf", "blessed_sisters", "Piercing Assault", "ap_bonus", 0))).is_equal(1)
	# Crack: on-6-to-hit AP bonus (a per-die effect; the Rending/Destructive machinery parametrised).
	assert_int(int(RulesRegistry.param("gf", "high_elf_fleets", "Crack", "on6_ap", 0))).is_equal(2)
	for r in ["Shatter", "Tear", "Melee Slayer", "Disintegrate", "Piercing Assault", "Crack"]:
		assert_bool(RulesRegistry.modeled_tokens("gf").has(r)).override_failure_message("%s not modeled" % r).is_true()
	# Melee Evasion (the melee-only Evasive) is also modeled + system-scoped.
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Melee Evasion")).is_true()
	assert_int(int(RulesRegistry.param("gf", "dark_elf_raiders", "Melee Evasion", "hit_penalty", 0))).is_equal(1)
	# Precise (attacker-side flat +1 to hit).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Precise")).is_true()
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Precise", "hit_bonus", 0))).is_equal(1)
	# Fortified (defender-side incoming AP reduction).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Fortified")).is_true()
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Fortified", "incoming_ap_reduction", 0))).is_equal(1)
	# Rapid Rush (quick-win batch: +6" on Rush actions — bands via MovementRangeController).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Rapid Rush")).is_true()
	assert_int(int(RulesRegistry.param("gf", "battle_brothers", "Rapid Rush", "rush_mod", 0))).is_equal(6)
	# Steadfast (quick-win batch: byte-identical to Battleborn — round-start Shaken recovery on 4+).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Steadfast")).is_true()
	assert_int(int(RulesRegistry.param("gf", "custodian_brothers", "Steadfast", "recover_target", 0))).is_equal(4)
	# No Retreat (quick-win batch: failed Shaken/Rout test counts as passed, paid in 1-3 self-wounds).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("No Retreat")).is_true()
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "No Retreat", "self_wound_max", 0))).is_equal(3)
	assert_bool(bool(RulesRegistry.param("gf", "alien_hives", "No Retreat", "bypass_regen", false))).is_true()
	# Guarded (quick-win batch: +1 defense when shot/charged from over 9"). GFF prints no such rule —
	# its map must NOT automate it (source-driven scoping, no cross-system bleed).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Guarded")).is_true()
	assert_int(int(RulesRegistry.param("gf", "blessed_sisters", "Guarded", "defense_bonus", 0))).is_equal(1)
	assert_float(float(RulesRegistry.param("gf", "blessed_sisters", "Guarded", "over_in", 0.0))).is_equal_approx(9.0, 0.001)
	# Coverage wave: gff books alias the Guarded primitive now (Sturdy-family), so the TOKEN is
	# present there too — system scoping keeps holding at lookup level.
	assert_bool(RulesRegistry.modeled_tokens("gff").has("Guarded")).is_true()
	# Shrouding family (denial primitives): -6" shooting range / -3" charge movement, floored at 6".
	assert_float(float(RulesRegistry.param("gf", "custodian_brothers", "Ranged Shrouding", "range_penalty_in", 0.0))).is_equal_approx(6.0, 0.001)
	assert_float(float(RulesRegistry.param("gf", "custodian_brothers", "Ranged Shrouding", "floor_in", 0.0))).is_equal_approx(6.0, 0.001)
	assert_float(float(RulesRegistry.param("gf", "battle_brothers", "Melee Shrouding", "move_penalty_in", 0.0))).is_equal_approx(3.0, 0.001)
	for r in ["Ranged Shrouding", "Melee Shrouding"]:
		assert_bool(RulesRegistry.modeled_tokens("gf").has(r)).override_failure_message("%s not modeled" % r).is_true()
	# Data-lag closures: Versatile Attack + Infiltrate ran in code for waves already — the maps now
	# say so (kills their false "not automated — apply manually" notices).
	assert_int(int(RulesRegistry.param("gf", "battle_brothers", "Versatile Attack", "ap_bonus", 0))).is_equal(1)
	assert_float(float(RulesRegistry.param("gf", "battle_brothers", "Versatile Attack", "over_in", 0.0))).is_equal_approx(9.0, 0.001)
	assert_str(str(RulesRegistry.param("gf", "alien_hives", "Infiltrate", "counts_as", ""))).is_equal("Ambush")
	assert_float(float(RulesRegistry.param("gf", "alien_hives", "Infiltrate", "min_enemy_dist_in", 0.0))).is_equal_approx(3.0, 0.001)
	for r in ["Versatile Attack", "Infiltrate"]:
		assert_bool(RulesRegistry.modeled_tokens("gf").has(r)).override_failure_message("%s not modeled" % r).is_true()
	# Grill round 2 cut A: Unpredictable (the generic "when attacking" die — 1-3 AP(+1), 4-6 +1 hit).
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Unpredictable", "ap_bonus", 0))).is_equal(1)
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Unpredictable", "low_roll_max", 0))).is_equal(3)
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Unpredictable")).is_true()
	# Sim-wave finding: an ALIASED rule (Ferocious -> Surge) must be modeled under its own NAME too —
	# the not-automated notice matches unit rule names, so a primitives-only set still printed it.
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Ferocious")).is_true()
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Surge")).is_true()
	# Unpredictable Shooter (autonomous wave): the shooting-only half of the attack die.
	assert_int(int(RulesRegistry.param("gf", "goblin_reclaimers", "Unpredictable Shooter", "ap_bonus", 0))).is_equal(1)
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Unpredictable Shooter")).is_true()
	# Hit & Run halves (after-shoot only / after-melee only).
	assert_str(str(RulesRegistry.param("gf", "custodian_brothers", "Hit & Run Shooter", "after", ""))).is_equal("shoot")
	assert_str(str(RulesRegistry.param("gf", "alien_hives", "Hit & Run Fighter", "after", ""))).is_equal("melee")
	# Range-gated conditional AP (Piercing Hunter / Slayer).
	assert_str(str(RulesRegistry.param("gf", "blessed_sisters", "Piercing Hunter", "condition", ""))).is_equal("ranged_over")
	assert_str(str(RulesRegistry.param("gf", "dao_union", "Slayer", "gate", ""))).is_equal("ranged_over_or_charge")
	# Heavy Impact(X): rated second impact pool at AP(1).
	assert_int(int(RulesRegistry.param("gf", "ratmen_clans", "Heavy Impact", "ap", 0))).is_equal(1)
	# Ravage(X): direct wounds on 6+ during the bearer's melee turn (rated, no save).
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Ravage", "wound_target", 0))).is_equal(6)
	assert_bool(bool(RulesRegistry.param("gf", "alien_hives", "Ravage", "no_save", false))).is_true()
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Ravage")).is_true()
	# Quick Shot: shoot after Rush (decision-level band swap).
	assert_bool(bool(RulesRegistry.param("gf", "goblin_reclaimers", "Quick Shot", "shoot_after_rush", false))).is_true()
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Quick Shot")).is_true()
	# Mend: pre-attack D3 heal on a friendly Tough model within 3".
	assert_float(float(RulesRegistry.param("gf", "battle_brothers", "Mend", "range_in", 0.0))).is_equal_approx(3.0, 0.001)
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Mend")).is_true()
	# Breath Attack: pre-attack 2+ for one Blast(3)/AP(1) hit at 6"/LOS.
	assert_int(int(RulesRegistry.param("gf", "alien_hives", "Breath Attack", "blast", 0))).is_equal(3)
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Breath Attack")).is_true()
	# Repel Ambushers: enemy Ambushers must arrive over 12" away from the bearer's unit.
	assert_float(float(RulesRegistry.param("gf", "human_defense_force", "Repel Ambushers", "min_dist_in", 0.0))).is_equal_approx(12.0, 0.001)
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Repel Ambushers")).is_true()
	# Movement trio (cut C): Bounding / Teleport / Hit & Run.
	assert_float(float(RulesRegistry.param("gf", "eternal_dynasty", "Teleport", "rush_bonus_in", 0.0))).is_equal_approx(6.0, 0.001)
	assert_float(float(RulesRegistry.param("gf", "custodian_brothers", "Hit & Run", "move_in", 0.0))).is_equal_approx(3.0, 0.001)
	for r in ["Bounding", "Teleport", "Hit & Run"]:
		assert_bool(RulesRegistry.modeled_tokens("gf").has(r)).override_failure_message("%s not modeled" % r).is_true()
	# Wahl-effect wave: Versatile Reach (+4" range OR +2" charge) and Versatile Defense (def half
	# played consistently — Guarded machinery; default_mode is data for the future EV switch).
	assert_float(float(RulesRegistry.param("gf", "battle_brothers", "Versatile Reach", "range_bonus_in", 0.0))).is_equal_approx(4.0, 0.001)
	assert_float(float(RulesRegistry.param("gf", "battle_brothers", "Versatile Reach", "charge_bonus_in", 0.0))).is_equal_approx(2.0, 0.001)
	assert_str(str(RulesRegistry.param("gf", "change_disciples", "Versatile Defense", "default_mode", ""))).is_equal("def")
	for r in ["Versatile Reach", "Versatile Defense"]:
		assert_bool(RulesRegistry.modeled_tokens("gf").has(r)).override_failure_message("%s not modeled" % r).is_true()
	# Vanguard: post-deploy 9" placement (pushed toward the enemy side by the AI).
	assert_float(float(RulesRegistry.param("gf", "dark_elf_raiders", "Vanguard", "place_in", 0.0))).is_equal_approx(9.0, 0.001)
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Vanguard")).is_true()


func test_retaliate_modeled_with_rating_params() -> void:
	# Wave 7: Retaliate(X) — "attacker takes X hits per wound taken" (melee-reaktiv).
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Retaliate")).is_true()
	assert_str(str(RulesRegistry.param("gf", "alien_hives", "Retaliate", "hits_per_wound", ""))).is_equal("X")


func test_redeployment_modeled_with_max_units() -> void:
	# Wave 7: Re-Deployment — "remove up to two friendly units ... deploy them again".
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Re-Deployment")).is_true()
	assert_int(int(RulesRegistry.param("gf", "battle_brothers", "Re-Deployment", "max_units", 0))).is_equal(2)


# === Coverage wave (2026-07-23): the generic alias layer ===

func test_rule_rating_parses_and_falls_back() -> void:
	assert_int(RulesRegistry.rule_rating("Retaliate(3)")).is_equal(3)
	assert_int(RulesRegistry.rule_rating("Crossing Attack(2)")).is_equal(2)
	assert_int(RulesRegistry.rule_rating("Fearless", 7)).is_equal(7)
	assert_int(RulesRegistry.rule_rating("Weird(x)", 5)).is_equal(5)


func test_unit_rules_of_primitive_resolves_data_aliases() -> void:
	# A synthetic map: "Plaguebound" aliases the Regeneration primitive at 6+; "Courage Aura"
	# aliases Banner. The layer must surface BOTH direct and item-granted rules, once each.
	RulesRegistry.reset_cache()
	RulesRegistry._cache["gf"] = {"factions": {"testfac": {
		"Plaguebound": {"primitive": "Regeneration", "params": {"ignore_target": 6, "all_models": true}},
		"Courage Aura": {"primitive": "Banner", "params": {"morale_bonus": 1}},
		"Fluffword": {"primitive": null},
	}}, "common": {}}
	var u := GameUnit.new()
	u.unit_properties = {"game_system": "gf", "faction_folder": "testfac",
		"special_rules": ["Plaguebound", "Fluffword", "Plaguebound"],
		"item_grants": {"Standard": ["Courage Aura"]}}
	var regen := RulesRegistry.unit_rules_of_primitive(u, "Regeneration")
	assert_int(regen.size()).is_equal(1)   # deduped
	assert_int(int(((regen[0] as Dictionary)["params"] as Dictionary)["ignore_target"])).is_equal(6)
	var banner := RulesRegistry.unit_rules_of_primitive(u, "Banner")
	assert_int(banner.size()).is_equal(1)  # item-granted counts
	assert_int(int(RulesRegistry.best_primitive_param(u, "Regeneration", "ignore_target", 5))).is_equal(6)
	assert_int(int(RulesRegistry.best_primitive_param(u, "Ravage", "wound_target", 6))).is_equal(6)  # absent family → fallback
	RulesRegistry.reset_cache()


func _inject_gf_map(fac: Dictionary) -> void:
	RulesRegistry.reset_cache()
	RulesRegistry._cache["gf"] = {"factions": {"testfac": fac}, "common": {}}


func test_regen_alias_params_flow_from_emitted_maps() -> void:
	# The REAL emitted map must carry the per-rule alias params (exporter precedence fix): a
	# Plaguebound unit regenerates at 6+, never at the Regeneration default 5+.
	RulesRegistry.reset_cache()
	var e := RulesRegistry.lookup("gf", "lust_disciples", "Lustbound")
	assert_str(str(e.get("primitive"))).is_equal("Royal Legion")
	assert_int(int((e.get("params", {}) as Dictionary).get("range_bonus_in", 0))).is_equal(4)
	var plague := RulesRegistry.lookup("gf", "plague_disciples", "Plaguebound")
	if plague.is_empty():   # faction slug probe — the rule lives in several chaos books
		for fac in ["plague_disciples", "wormhole_daemons_of_plague", "havoc_brothers"]:
			plague = RulesRegistry.lookup("gf", fac, "Plaguebound")
			if not plague.is_empty():
				break
	assert_bool(not plague.is_empty()).is_true()
	assert_int(int((plague.get("params", {}) as Dictionary).get("ignore_target", 0))).is_equal(6)
	RulesRegistry.reset_cache()


func test_second_wind_candidate_and_cap() -> void:
	_inject_gf_map({"Inquisitorial Agent": {"primitive": "Second Wind",
		"params": {"uses_per_game": 1, "army_cap_fraction": 3}}})
	var a := GameUnit.new()
	a.unit_id = "a"
	a.unit_properties = {"game_system": "gf", "faction_folder": "testfac", "player_id": 2,
		"special_rules": ["Inquisitorial Agent"], "name": "A", "quality": 4, "defense": 4}
	var m := ModelInstance.new()
	m.is_alive = true
	var n := Node3D.new()
	add_child(n)
	m.node = n
	a.models.append(m)
	a.is_activated = true
	var army: OPRArmyManager = auto_free(OPRArmyManager.new())
	army.game_units = {a.unit_id: a}
	army.current_round = 1
	var solo: SoloController = auto_free(SoloController.new())
	add_child(solo)
	solo.setup(army, null, null, 1, 2)
	var cand := solo.second_wind_candidate()
	assert_object(cand).is_equal(a)                       # activated carrier, unused → candidate
	assert_str(solo.spend_second_wind(a)).is_equal("Inquisitorial Agent")
	assert_bool(a.is_activated).is_false()                # may act again
	assert_bool(a.is_fatigued).is_false()                 # fatigue cleared per text
	a.is_activated = true
	assert_object(solo.second_wind_candidate()).is_null() # once per game — used
	RulesRegistry.reset_cache()


func test_growth_marker_state_math() -> void:
	_inject_gf_map({"Defensive Frenzy": {"primitive": "Growth Markers",
		"params": {"on_kill": true, "max_markers": 2, "defense_per_marker": 1}},
		"Piercing Growth": {"primitive": "Growth Markers",
		"params": {"per_round": true, "max_markers": 4, "ap_per_two": 1}}})
	var u := GameUnit.new()
	u.unit_properties = {"game_system": "gf", "faction_folder": "testfac",
		"special_rules": ["Defensive Frenzy", "Piercing Growth"],
		"growth_defensive_frenzy": 2, "growth_piercing_growth": 3}
	var rules := RulesRegistry.unit_rules_of_primitive(u, "Growth Markers")
	assert_int(rules.size()).is_equal(2)
	RulesRegistry.reset_cache()


func test_shot_modifier_and_stealth_alias_entries_resolve() -> void:
	_inject_gf_map({"Bad Shot": {"primitive": "Shot Modifier", "params": {"hit_bonus": -1}},
		"Machine-Fog": {"primitive": "Stealth", "params": {"hit_penalty": 1, "over_in": 9, "applies_charged": true}}})
	var u := GameUnit.new()
	u.unit_properties = {"game_system": "gf", "faction_folder": "testfac",
		"special_rules": ["Bad Shot", "Machine-Fog"]}
	assert_int(int(RulesRegistry.best_primitive_param(u, "Shot Modifier", "hit_bonus", 0))).is_equal(-1)
	var st := RulesRegistry.unit_rules_of_primitive(u, "Stealth")
	assert_int(st.size()).is_equal(1)
	assert_bool(bool(((st[0] as Dictionary)["params"] as Dictionary).get("applies_charged", false))).is_true()
	RulesRegistry.reset_cache()


## Resolver wave A (2026-07-24): the 17 planned combat mechanics flipped to automated — the
## EMITTED maps must resolve them with primitive + params intact (real book/faction pairs).
func test_wave_a_flipped_rules_resolve_from_emitted_maps() -> void:
	var cases: Array = [
		["gf", "human_inquisition", "Takedown Shot", "Takedown", "extra_attack_q", 2],
		["gf", "alien_hives", "Takedown Strike", "Takedown", "ap", 2],
		["gf", "orc_marauders", "Rending Mark", "Utility Buff", "vs_target", true],
		["gf", "wormhole_daemons_of_war", "Fatigue Debuff", "Mind Control", "effect", "fatigue"],
		["gf", "ratmen_clans", "Hazardous", "Hazardous", "ap", 4],
		["gf", "goblin_reclaimers", "Instinctive", "Instinctive", "hit_bonus", 1],
		["gf", "eternal_dynasty", "Vengeance", "Vengeance", "hit_bonus_per_marker", 1],
		["gf", "alien_hives", "Self-Destruct", "Self-Destruct", "trigger", "death_in_melee_or_post_m"],
		["gf", "high_elf_fleets", "Unwieldy", "Unwieldy", "strikes_last", true],
		["aof", "rift_daemons_of_war", "Reckless Piercing", "Reckless Piercing", "roll_target", 2],
		["aof", "war_disciples", "Bloodthirsty Fighter", "Bloodthirsty Fighter", "melee_only", true],
		["aof", "dark_elves", "Retreating Strike", "Ravage", "trigger", "post_melee_move"],
	]
	for c in cases:
		var entry := RulesRegistry.lookup(str(c[0]), str(c[1]), str(c[2]))
		assert_str(str(entry.get("primitive", ""))) \
			.override_failure_message("%s/%s/%s lost its primitive" % [c[0], c[1], c[2]]).is_equal(str(c[3]))
		var params: Dictionary = entry.get("params", {})
		# JSON numbers parse as float — compare with the ".0" stripped so 2 == 2.0.
		assert_str(str(params.get(str(c[4]))).trim_suffix(".0")) \
			.override_failure_message("%s/%s/%s param %s" % [c[0], c[1], c[2], c[4]]).is_equal(str(c[5]).trim_suffix(".0"))


## Wave A: the alias layer resolves the flipped rules through unit_rules_of_primitive (the seam
## every resolver queries) — one book-true unit per family leg.
func test_wave_a_unit_primitive_resolution() -> void:
	var u := _unit_with(["Takedown Strike", "Vengeance", "Unwieldy"], "gf", "alien_hives")
	assert_int(RulesRegistry.unit_rules_of_primitive(u, "Takedown").size()).is_equal(1)
	var v := _unit_with(["Vengeance"], "gf", "eternal_dynasty")
	assert_int(RulesRegistry.unit_rules_of_primitive(v, "Vengeance").size()).is_equal(1)
	var r := _unit_with(["Retreating Strike"], "aof", "dark_elves")
	var rr := RulesRegistry.unit_rules_of_primitive(r, "Ravage")
	assert_int(rr.size()).is_equal(1)
	assert_str(str(((rr[0] as Dictionary).get("params", {}) as Dictionary).get("trigger", ""))).is_equal("post_melee_move")
