extends GdUnitTestSuite
## Solo-AI wave 5 — RulesRegistry: the system-scoped mechanics-map loader (assets/solo/
## rules_mechanics_<system>.json, generated by tools/rules_mechanics_export.py). Proves the HARD
## invariant (lookup by (system, faction, name) with a common fallback — never name-only across
## systems), the system-scoped parameter divergences, the derived modeled/decision token sets, and
## the committed maps' text-hygiene (no OPR rule bodies in the public repo).


func _unit_with(rules: Array, system: String = "", faction: String = "", defense: int = 4) -> GameUnit:
	var u := GameUnit.new()
	u.unit_id = "t_%d" % rules.size()
	u.unit_properties = {"player_id": 2, "name": "T", "quality": 4, "defense": defense,
		"special_rules": rules}
	if not system.is_empty():
		u.unit_properties["game_system"] = system
	if not faction.is_empty():
		u.unit_properties["faction_folder"] = faction
	var m := ModelInstance.new()
	m.is_alive = true
	u.models.append(m)
	return u


func test_all_five_system_maps_load() -> void:
	for s in RulesRegistry.SYSTEMS:
		var m := RulesRegistry.map_for(str(s))
		assert_bool(m.is_empty()).override_failure_message("map missing for %s" % s).is_false()
		assert_bool((m.get("common", {}) as Dictionary).is_empty()).is_false()
		assert_bool((m.get("modeled", []) as Array).is_empty()).is_false()


func test_lookup_falls_back_from_faction_to_common() -> void:
	# "AP" is a core rule: not in the faction section → resolved via the system's common section.
	var entry := RulesRegistry.lookup("gf", "human_defense_force", "AP")
	assert_str(str(entry.get("primitive", ""))).is_equal("AP")
	# A faction-level rule resolves from the faction's own section.
	var shred := RulesRegistry.lookup("gf", "alien_hives", "Shred")
	assert_str(str(shred.get("primitive", ""))).is_equal("Shred")
	# Unknown rules yield an empty entry (callers use their fallbacks).
	assert_bool(RulesRegistry.lookup("gf", "alien_hives", "No Such Rule").is_empty()).is_true()


func test_system_scoping_banner_and_musician_params_diverge() -> void:
	# THE cross-system divergence proof (wave-5 gate 4): the full-scale games (GF / AoF / AoF
	# Regiments) grant Banner/Musician to the bearer's UNIT; the skirmish-scale games (GFF / AoF
	# Skirmish) rewrite them to "bearer + up to 3 picked friendly units". Same rule NAME — different
	# parameters per system, so a name-only lookup would be WRONG.
	for s in ["gf", "aof", "aofr"]:
		assert_str(str(RulesRegistry.param(str(s), "", "Banner", "scope", ""))).is_equal("unit")
		assert_str(str(RulesRegistry.param(str(s), "", "Musician", "scope", ""))).is_equal("unit")
		assert_int(int(RulesRegistry.param(str(s), "", "Banner", "picked_units", 0))).is_equal(0)
	for s in ["gff", "aofs"]:
		assert_str(str(RulesRegistry.param(str(s), "", "Banner", "scope", ""))).is_equal("picked")
		assert_str(str(RulesRegistry.param(str(s), "", "Musician", "scope", ""))).is_equal("picked")
		assert_int(int(RulesRegistry.param(str(s), "", "Banner", "picked_units", 0))).is_equal(3)
	# The bonus itself is identical everywhere (+1) — only the scope diverges.
	for s in RulesRegistry.SYSTEMS:
		assert_int(int(RulesRegistry.param(str(s), "", "Banner", "morale_bonus", 0))).is_equal(1)


func test_modeled_tokens_are_system_scoped() -> void:
	# Royal Legion (Mummified Undead) is an AoF-family army-book rule: modeled in aof, NOT in gf —
	# the derived sets never bleed a rule across systems whose books don't field it.
	assert_bool(RulesRegistry.modeled_tokens("aof").has("Royal Legion")).is_true()
	assert_bool(RulesRegistry.modeled_tokens("gf").has("Royal Legion")).is_false()
	# The shared core primitives are modeled everywhere, incl. the wave-5 set.
	for s in RulesRegistry.SYSTEMS:
		var tokens := RulesRegistry.modeled_tokens(str(s))
		for t in ["AP", "Tough", "Shred", "Indirect", "Banner", "Musician", "Sergeant", "Limited", "Armor"]:
			assert_bool(tokens.has(t)).override_failure_message("%s missing in %s" % [t, s]).is_true()
		assert_bool(RulesRegistry.decision_tokens(str(s)).has("Indirect")).is_true()


func test_param_returns_fallback_when_absent() -> void:
	assert_int(int(RulesRegistry.param("gf", "", "AP", "no_such_param", 42))).is_equal(42)
	assert_int(int(RulesRegistry.param("gf", "", "No Such Rule", "x", 7))).is_equal(7)
	# Unknown system slugs normalize to the default system instead of crashing.
	assert_str(RulesRegistry.normalize_system("bogus")).is_equal(RulesRegistry.DEFAULT_SYSTEM)
	assert_str(RulesRegistry.normalize_system("AOFS ")).is_equal("aofs")


func test_unit_addressing_reads_import_properties() -> void:
	var u := _unit_with(["Banner"], "gff", "human_empire")
	assert_str(RulesRegistry.system_of_unit(u)).is_equal("gff")
	assert_str(RulesRegistry.faction_of_unit(u)).is_equal("human_empire")
	# The unit-addressed param resolves under ITS system: gff Banner = the picked-units variant.
	assert_str(str(RulesRegistry.unit_param(u, "Banner", "scope", ""))).is_equal("picked")
	# A unit without import metadata falls back to the default system, not a crash.
	var bare := _unit_with(["Banner"])
	assert_str(RulesRegistry.system_of_unit(bare)).is_equal(RulesRegistry.DEFAULT_SYSTEM)
	assert_str(str(RulesRegistry.unit_param(bare, "Banner", "scope", ""))).is_equal("unit")


func test_unit_rule_active_is_system_scoped() -> void:
	# Banner is a core rule → active in every system for a bearer.
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Banner"], "gf"), "Banner")).is_true()
	# Royal Legion: active for the AoF book that fields it, NOT for a gf unit (no gf book has it).
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Royal Legion"], "aof", "mummified_undead"), "Royal Legion")).is_true()
	assert_bool(RulesRegistry.unit_rule_active(_unit_with(["Royal Legion"], "gf", "human_defense_force"), "Royal Legion")).is_false()
	# Not carrying the rule at all → inactive, whatever the map says.
	assert_bool(RulesRegistry.unit_rule_active(_unit_with([], "gf"), "Banner")).is_false()


func test_committed_maps_carry_no_rule_texts() -> void:
	# Public-repo IP guard (maintainer-ruled): the maps are DERIVED mechanics — rule names + our own
	# primitive/param encoding. No entry may carry a text-ish key, and no param string may be prose.
	var forbidden := ["official_text", "text", "description", "reason", "citation", "_license"]
	for s in RulesRegistry.SYSTEMS:
		var m := RulesRegistry.map_for(str(s))
		var sections: Array = [m.get("common", {})]
		for fmap in (m.get("factions", {}) as Dictionary).values():
			sections.append(fmap)
		for section in sections:
			for rule_name in (section as Dictionary):
				var entry := (section as Dictionary)[rule_name] as Dictionary
				for key in forbidden:
					assert_bool(entry.has(key)).override_failure_message(
						"%s/%s carries forbidden key %s" % [s, rule_name, key]).is_false()
				for pv in (entry.get("params", {}) as Dictionary).values():
					if pv is String:
						assert_bool((pv as String).length() <= 24 and not (pv as String).contains(". ")) \
							.override_failure_message("prose-like param in %s/%s: %s" % [s, rule_name, pv]).is_true()


func test_regen_and_fearless_params_match_the_wave14_constants() -> void:
	# The byte-identical seam: where wave-1..4 dice math now READS the map, the data must equal the
	# constants it replaced (Regeneration 5+, Self-Repair 6+, Fearless 4+, Royal Legion +4").
	assert_int(int(RulesRegistry.param("gf", "", "Regeneration", "ignore_target", 0))).is_equal(5)
	assert_int(int(RulesRegistry.param("gf", "robot_legions", "Self-Repair", "ignore_target", 0))).is_equal(6)
	assert_int(int(RulesRegistry.param("gf", "", "Fearless", "recover_target", 0))).is_equal(4)
	assert_int(int(RulesRegistry.param("aof", "mummified_undead", "Royal Legion", "range_bonus_in", 0))).is_equal(4)
