extends GdUnitTestSuite
## Solo-AI wave 6 — SpellsRegistry: the system-scoped faction spell-map loader
## (assets/solo/spells_mechanics_<system>.json, generated by tools/spells_mechanics_export.py).
## Proves the HARD invariant (spell lists resolve by (system, faction) — the SAME faction's list
## diverges across systems), the BOOK-ORDER guarantee (the official D3+X pick indexes it), the
## committed maps' text-hygiene (no OPR spell prose in the public repo) and the unit-addressed seam.


func _unit_with(system: String, faction: String, rules: Array = ["Caster(2)"]) -> GameUnit:
	var u := GameUnit.new()
	u.unit_id = "t_%s_%s" % [system, faction]
	u.unit_properties = {"player_id": 2, "name": "T", "quality": 4, "defense": 4,
		"special_rules": rules, "game_system": system, "faction_folder": faction}
	var m := ModelInstance.new()
	m.is_alive = true
	u.models.append(m)
	return u


func test_all_five_system_maps_load_with_factions() -> void:
	for s in RulesRegistry.SYSTEMS:
		var m := SpellsRegistry.map_for(str(s))
		assert_bool(m.is_empty()).override_failure_message("spell map missing for %s" % s).is_false()
		assert_bool((m.get("factions", {}) as Dictionary).is_empty()) \
			.override_failure_message("no factions in spell map %s" % s).is_false()


func test_lookup_is_system_and_faction_scoped() -> void:
	# A real faction resolves; an unknown faction (or empty) falls back to [] — never a guess.
	assert_bool(SpellsRegistry.spells_for("aof", "high_elves").is_empty()).is_false()
	assert_bool(SpellsRegistry.spells_for("aof", "no_such_faction").is_empty()).is_true()
	assert_bool(SpellsRegistry.spells_for("aof", "").is_empty()).is_true()


func test_spell_lists_diverge_across_systems_for_the_same_faction() -> void:
	# THE cross-system divergence proof (the wave-6 §0 invariant, measured on the source data: 77 of
	# 82 books published for 2+ systems carry parameter-divergent spell lists). Alien Hives' first
	# spell targets ONE friendly unit in Grimdark Future but UP TO TWO in GF: Firefight — same spell
	# name, different mechanics, so a faction-only (system-less) lookup would resolve WRONG data.
	var gf_first: Dictionary = SpellsRegistry.spells_for("gf", "alien_hives")[0]
	var gff_first: Dictionary = SpellsRegistry.spells_for("gff", "alien_hives")[0]
	assert_str(str(gf_first.get("name", ""))).is_equal(str(gff_first.get("name", "")))
	assert_int(int((gf_first.get("target", {}) as Dictionary).get("count", 0))).is_equal(1)
	assert_int(int((gff_first.get("target", {}) as Dictionary).get("count", 0))).is_equal(2)


func test_lists_are_book_ordered_with_mixed_thresholds() -> void:
	# The committed order IS rule data: the official Solo v3.5.0 D3+X pick indexes the PRINTED list.
	# High Elves (AoF) field the documented six: thresholds run 1,1,2,2,3,3 in book order.
	var spells := SpellsRegistry.spells_for("aof", "high_elves")
	assert_int(spells.size()).is_equal(6)
	var thresholds: Array = []
	for sp in spells:
		thresholds.append(int((sp as Dictionary).get("threshold", 0)))
	assert_array(thresholds).is_equal([1, 1, 2, 2, 3, 3])
	# The design-doc reference entries resolve with their verified mechanics.
	var arcane: Dictionary = SpellsRegistry.entry_for("aof", "high_elves", "Arcane Blast")
	assert_str(str(arcane.get("status", ""))).is_equal("modeled")
	assert_int(int(arcane.get("range_in", 0))).is_equal(18)
	assert_array((arcane.get("effect", {}) as Dictionary).get("weapon_rules", [])).contains(["Blast(3)"])


func test_spells_for_unit_reads_the_import_seams() -> void:
	# The unit-addressed lookup reads game_system + faction_folder — the SAME seams RulesRegistry
	# uses, so spells and rules always resolve for one consistent (system, faction).
	var he := _unit_with("aof", "high_elves")
	assert_bool(SpellsRegistry.spells_for_unit(he).is_empty()).is_false()
	var unknown := _unit_with("aof", "no_such_faction")
	assert_bool(SpellsRegistry.spells_for_unit(unknown).is_empty()).is_true()


func test_committed_maps_carry_no_spell_prose() -> void:
	# Public-repo hygiene: the committed maps hold NAMES + numeric mechanics only. No string value
	# anywhere may look like rule prose (sentence punctuation / length) and the effect-text keys of
	# the source data must never appear.
	for s in RulesRegistry.SYSTEMS:
		var m := SpellsRegistry.map_for(str(s))
		var factions: Dictionary = m.get("factions", {})
		for faction in factions:
			for sp in (factions[faction] as Dictionary).get("spells", []):
				var spell := sp as Dictionary
				assert_bool(spell.has("effect_text") or spell.has("official_effect") \
					or spell.has("description") or spell.has("citation")).is_false()
				_assert_no_prose(spell, "%s/%s/%s" % [s, faction, spell.get("name", "?")])


func _assert_no_prose(value: Variant, ctx: String) -> void:
	if value is Dictionary:
		for k in value:
			_assert_no_prose(value[k], ctx)
	elif value is Array:
		for v in value:
			_assert_no_prose(v, ctx)
	elif value is String:
		var s := value as String
		assert_bool(s.length() > 40 or s.contains(". ")) \
			.override_failure_message("prose leaked into %s: %s" % [ctx, s]).is_false()


func test_caster_rule_resolves_system_scoped_in_the_rules_maps() -> void:
	# Wave 6 wires Caster(X) into the RULES maps too (the token economy is per-system DATA): the
	# core entry resolves in every system with the v3.5.1 parameters, so the unmodeled-rules log
	# stops flagging Caster wherever the automation now casts.
	for s in RulesRegistry.SYSTEMS:
		var entry := RulesRegistry.lookup(str(s), "", "Caster")
		assert_str(str(entry.get("primitive", ""))).override_failure_message(
			"Caster unresolved for %s" % s).is_equal("Caster")
		assert_int(int(RulesRegistry.param(str(s), "", "Caster", "token_cap", 0))).is_equal(6)
		assert_int(int(RulesRegistry.param(str(s), "", "Caster", "cast_target", 0))).is_equal(4)
		assert_float(float(RulesRegistry.param(str(s), "", "Caster", "aura_in", 0.0))).is_equal(18.0)
