//! NML-1158b — the `state_phi` / `logit` TWIN is pinned to ONE committed
//! fixture (`test/fixtures/policy_twin/state_phi_twin.json`, regenerated by
//! tools/policy_twin/gen_state_phi_twin.py, never by hand). The GDScript twin
//! (scripts/solo/policy_order.gd) asserts the SAME numbers in
//! test/policy_order_twin_test.gd, so a drift in either twin fails its own
//! side of the pin.
use nml_core::policy::{PolicyNet, state_phi};
use serde_json::Value;

const FIXTURE: &str =
    include_str!("../../../test/fixtures/policy_twin/state_phi_twin.json");

#[test]
fn state_phi_and_logit_match_the_pinned_fixture() {
    let fx: Value = serde_json::from_str(FIXTURE).unwrap();
    let net: PolicyNet = serde_json::from_value(fx["net"].clone()).unwrap();
    let candidate: Vec<f64> = serde_json::from_value(fx["candidate"].clone()).unwrap();
    let mut cases = 0;
    for c in fx["cases"].as_array().unwrap() {
        cases += 1;
        let name = c["name"].as_str().unwrap();
        let side = c["side"].as_i64().unwrap();
        let board: Vec<Vec<f64>> = serde_json::from_value(
            fx["boards"][c["board"].as_str().unwrap()].clone()
        )
        .unwrap();
        let want_phi: Vec<f64> = serde_json::from_value(c["state_phi"].clone()).unwrap();
        let want_logit = c["logit"].as_f64().unwrap();
        // The play-time caller always uses actor_row = -1 (policy.rs:394-398),
        // the bug-compatible zero actor block the GDScript twin hard-wires.
        let phi = state_phi(&board, side, -1);
        assert_eq!(phi.len(), 93, "{name}: state_phi is 93 wide");
        assert_eq!(phi.len(), want_phi.len(), "{name}: pinned state_phi is 93 wide");
        for (i, g) in phi.iter().enumerate() {
            let gv = *g;
            let w = want_phi[i];
            assert!(
                (gv - w).abs() <= 1e-12,
                "{name}: state_phi[{i}] = {gv:.17} != pinned {w:.17}"
            );
        }
        let got = net.logit(&phi, &candidate);
        assert!(
            (got - want_logit).abs() <= 1e-12,
            "{name}: logit {got:.17} != pinned {want_logit:.17}"
        );
    }
    assert_eq!(cases, 4, "fixture carries both sides plus the empty board");
    eprintln!("state_phi_twin: {cases} pinned case(s) green");
}
