class_name ModelLibrary
extends Node
## Resolves OPR units to 3D model files that are delivered on demand.
##
## A small bundled manifest (assets/model_manifest.json, generated by Model Forge)
## maps a unit's identity -> { url, sha256, size }. The heavy GLBs live on a CDN
## (GitHub Releases) and are downloaded + cached only when an imported army needs
## them. Stats/base sizes still come from the OPR API; this only resolves models.
## See docs/ASSET_DELIVERY.md.

# === Constants ===

const BUNDLED_MANIFEST_PATH: String = "res://assets/model_manifest.json"

# === Private variables ===

var _downloader: AssetDownloadManager = null
var _models: Dictionary = {}   # key -> { url, sha256, size }
var _base_url: String = ""     # optional prefix for relative entry URLs

# === Lifecycle ===

func _ready() -> void:
	_downloader = AssetDownloadManager.new()
	_downloader.name = "AssetDownloadManager"
	add_child(_downloader)
	_load_bundled_manifest()

# === Public API ===

## Stable lookup key for a unit's model. The faction is the (already consistent)
## faction_folder, lowercased; the UNIT NAME is also separator-insensitive so the OPR
## name ("Heavy Exo-Suit") matches a manifest key generated from a slug-derived name
## ("Heavy Exo Suit") — hyphens/underscores/extra spaces in the unit name are folded.
static func make_key(faction: String, unit_name: String) -> String:
	return "%s/%s" % [faction.strip_edges().to_lower(), _normalize_unit(unit_name)]


## Lowercase a unit name, fold -/_ to spaces, collapse repeats. Both sides of the lookup.
static func _normalize_unit(s: String) -> String:
	var t := s.strip_edges().to_lower().replace("-", " ").replace("_", " ")
	while t.contains("  "):
		t = t.replace("  ", " ")
	return t


func has_model(faction: String, unit_name: String) -> bool:
	return _models.has(make_key(faction, unit_name))


## Returns the local path if the unit's model is already cached, else "" (sync).
func get_cached_path(faction: String, unit_name: String) -> String:
	var entry: Dictionary = _entry(faction, unit_name)
	if entry.is_empty():
		return ""
	var sha: String = entry.get("sha256", "")
	return _downloader.cache_path(sha) if _downloader.is_cached(sha) else ""


## Ensures the unit's model is cached (downloads if needed). Awaitable. Returns path or "".
func ensure_model(faction: String, unit_name: String) -> String:
	var entry: Dictionary = _entry(faction, unit_name)
	if entry.is_empty():
		return ""
	return await _downloader.ensure(_resolve_url(entry), entry.get("sha256", ""))


## Ensures all of an army's models are cached up front (one batch, with progress).
## unit_specs: Array of { "faction": String, "unit_name": String }. Awaitable.
func ensure_models(unit_specs: Array) -> void:
	if _models.is_empty():
		return
	var seen: Dictionary = {}
	var batch: Array = []
	for spec: Dictionary in unit_specs:
		var entry: Dictionary = _entry(spec.get("faction", ""), spec.get("unit_name", ""))
		if entry.is_empty():
			continue
		var sha: String = entry.get("sha256", "")
		if sha.is_empty() or seen.has(sha):
			continue
		seen[sha] = true
		batch.append({"url": _resolve_url(entry), "sha256": sha})
	if not batch.is_empty():
		await _downloader.ensure_batch(batch)

# === Private helpers ===

func _entry(faction: String, unit_name: String) -> Dictionary:
	return _models.get(make_key(faction, unit_name), {})


func _resolve_url(entry: Dictionary) -> String:
	var url: String = entry.get("url", "")
	if url.begins_with("http://") or url.begins_with("https://"):
		return url
	if not _base_url.is_empty():
		return _base_url.path_join(url)
	return url


func _load_bundled_manifest() -> void:
	if not FileAccess.file_exists(BUNDLED_MANIFEST_PATH):
		return
	apply_manifest_text(FileAccess.get_file_as_string(BUNDLED_MANIFEST_PATH))


## Parses a manifest JSON string into the in-memory index (also used by tests).
func apply_manifest_text(text: String) -> void:
	var data: Variant = JSON.parse_string(text)
	if typeof(data) != TYPE_DICTIONARY:
		return
	_base_url = data.get("base_url", "")
	var models: Variant = data.get("models", {})
	if typeof(models) == TYPE_DICTIONARY:
		# Re-key with the same normalisation make_key() uses, so manifest keys built from
		# slug-derived names still match the canonical OPR names at lookup time.
		_models = {}
		for k: String in models:
			var parts: PackedStringArray = k.split("/", true, 1)
			if parts.size() == 2:
				_models[make_key(parts[0], parts[1])] = models[k]
			else:
				_models[k] = models[k]
